[package]
name = "moore-vhdl"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[lib]
path = "lib.rs"

[dependencies]
moore-common = { path = "../common" }
moore-vhdl-syntax = { path = "syntax" }
# moore-vhdl-hir = { path = "hir" }
num = "0.1"
bincode = "0.6"
rustc-serialize = "0.3"
typed-arena = "1.3.0"
