[package]
name = "moore-common"
version = "0.1.0"
authors = ["Fabian Schuiki <fschuiki@iis.ee.ethz.ch>"]

[lib]
path = "lib.rs"

[dependencies]
memmap = "0.5.0"
rustc-serialize = "0.3.22"
serde = "1"
